### list groups

GET http://localhost:3333/groups

### get groups
GET http://localhost:3333/groups/group_zGC4RQcQQBNu6PRCPNuHi

### create groups
POST http://localhost:3333/groups
Content-Type: application/json

{
  "name": "Grupo 1",
  "userId": "user_6K8bVkoVb1vgOQrj9EpTG"
}

### update groups
PATCH http://localhost:3333/groups/group_RimlLCLOehpfWd6xZHYQI
Content-Type: application/json

{
  "name": "Grupo 2"
}

### delete groups
DELETE http://localhost:3333/groups/group_boeeTLrSP4onNXyADhwxc