### list users

GET http://localhost:3333/users

### get users
GET http://localhost:3333/users/user_mg0NtPt9XZRZAz12I02g

### create users
POST http://localhost:3333/users
Content-Type: application/json

{
  "email": "victormatheus507@gmail.com",
  "password": "1234"
}

### update users
PATCH http://localhost:3333/users/1
Content-Type: application/json

{
  "email": "victormatheus508@gmail.com"
}

### delete users
DELETE http://localhost:3333/users/user_g1Ggv_j_0Mr5ZxMTrSyGd