### list users

GET http://localhost:3333/user

### get users
GET http://localhost:3333/user/user_YO-Q4bC0rE8TocAZY7D7g

### create users
POST http://localhost:3333/user
Content-Type: application/json

{
  "email": "victormatheus507@gmail.com",
  "password": "1234"
}

### update users
PATCH http://localhost:3333/user/1
Content-Type: application/json

{
  "email": "victormatheus508@gmail.com"
}

### delete users
DELETE http://localhost:3333/user/user_VQvLQIyeu-gPc7cLJSn1-

