### list contacts

GET http://localhost:3333/contacts

### get contacts
GET http://localhost:3333/contacts/group_boeeTLrSP4onNXyADhwxc

### create contacts
POST http://localhost:3333/contacts
Content-Type: application/json

{
  "name": "victor",
  "phoneNumber": "5584988596033",
  "groupId": "group_boeeTLrSP4onNXyADhwxc"
}

### update contacts
PATCH http://localhost:3333/contacts/group_boeeTLrSP4onNXyADhwxc
Content-Type: application/json

{
  "name": "Victor"
}

### delete contacts
DELETE http://localhost:3333/contacts/contact__ogjqxwO68T6nrbfoekdF"